# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Dwonload"

# The default layout to use for your application (located in
# views/layouts/main.tt)
#layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_toolkit"

engines:
   template_toolkit:
      WRAPPER: layouts/main.tt
# template: "template_toolkit"
# engines:
#   template_toolkit:
#     encoding:  'utf8'
#     start_tag: '[%'
#     end_tag:   '%]'

#session handling

session: "Storable"

plugins:
   Database:
      driver: 'mysql'
      database: 'dwonload'
      host: 'localhost'
      port: 8889
      username: 'root'
      password: 'KoWd7pLBT'
      connection_check_threshold: 10
      dbi_params:
          RaiseError: 1
          AutoCommit: 1
          mysql_socket: '/var/run/mysqld/mysqld.sock'
      on_connect_do: ["SET NAMES 'utf8'", "SET CHARACTER SET 'utf8'" ]
      log_queries: 1
   Email:
      ssl: 1
      driver: smtp
      host: smtp.gmail.com
      port: 465
      user: freekkalter@gmail.com
      pass: dbxwuscstyywbgoq

